apiVersion: v1
kind: Service
metadata:
  name: aggService
spec:
  selector:
    app: aggService
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
          name: aggService
spec:
          replicas: 1
          selector:
            matchLabels:
              app: aggService
          template:
            metadata:
              labels:
                app: aggService
            spec:
              containers:
                - name: service1
                  image: rajeshramawat/aggservice
                  ports:
                    - containerPort: 8080
                  imagePullPolicy: Always