kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storage-demo-project
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: storage-demo-project
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: storage-demo-project
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-demo-project
spec:
  ports:
  - port: 3306
    selector:
        app: mysql-demo-project
    clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
    name: mysql
spec:
    selector:
    matchLabels:
        app: mysql
    strategy:
    type: Recreate
    template:
    metadata:
        labels:
        app: mysql
    spec:
        containers:
        - image: mysql:5.6
        name: mysql
        env:
            # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
            value: password
        ports:
        - containerPort: 3306
            name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
        volumes:
        - name: mysql-persistent-storage
        persistentVolumeClaim:
            claimName: mysql-pv-claim