kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storage-demo-project
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-demo-pvc
spec:
  storageClassName: storage-demo-project
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-demo-project
spec:
  selector:
    app: mysql-demo-project
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-demo-project
spec:
  selector:
    matchLabels:
      app: mysql-demo-project
  template:
    metadata:
      labels:
        app: mysql-demo-project
    spec:
      containers:
        - name: mysql-demo-project
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mysql-demo-pvc