apiVersion: v1
kind: ConfigMap
metadata:
  name: jaegerenv
data:
  jaeger-host: "10.0.10.64"
  jaeger-port: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
  labels:
    app: orderservice
spec:
  selector:
    app: orderservice
  ports:
  - port: 80
    name: http
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
      name: orderservice
spec:
      replicas: 1
      selector:
        matchLabels:
          app: orderservice
      template:
        metadata:
          labels:
            app: orderservice
        spec:
          containers:
            - name: orderservice
              image: rajeshramawat/orderservice
              ports:
                - containerPort: 8080
              env:
                - name: JAEGER_HOST
                  valueFrom: 
                        configMapKeyRef:
                            name: jaegerenv
                            key: jaeger-host
                - name: JAEGER_PORT
                  valueFrom: 
                        configMapKeyRef:
                            name: jaegerenv
                            key: jaeger-port
              imagePullPolicy: Always