kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storage-demo-project
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
kind: PersistentVolume
apiVersion: v1
metadata:
    name: mysql-pv-volume
    labels:
        type: local
spec:
    storageClassName: storage-demo-project
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 500Mi
    hostPath:
        path: /data/mysql
        type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pv-claim
    labels:
        app: mysqlpv
    spec:  
      accessModes:
        - ReadWriteOnce
      storageClassName: storage-demo-project
      resources:
            requests:
                storage: 500Mi