apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqldb
data:
  database-name: "restapi"
  database-service: "mysql-demo-project"
  database-port: "3306"
  database-password: "password"
  database-user: "root"
--- 
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb
type: generic
data:
  database-password: password
  database-user: root
---
apiVersion: v1
kind: Service
metadata:
    name: userservice
    labels:
        app: userservice
spec:
    selector:
        app: userservice
    ports:
        - port: 80
          name: http
          targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: rajeshramawat/userservice
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              valueFrom: 
                    configMapKeyRef:
                        name: mysqldb
                        key: database-service
            - name: MYSQL_PORT
              valueFrom: 
                    configMapKeyRef:
                        name: mysqldb
                        key: database-port
            - name: MYSQL_DB_NAME
              valueFrom: 
                    configMapKeyRef:
                        name: mysqldb
                        key: database-name
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                        name: mysqldb
                        key: database-user
            - name: PASSWORD
              valueFrom:
                configMapKeyRef:
                        name: mysqldb
                        key: database-password
            - name: JAEGER_UDP_HOST_WITH_PORT
              valueFrom: 
                    configMapKeyRef:
                        name: jaegerenv
                        key: jaeger-host-with-port
            - name: JAEGER_HTTP_URL
              valueFrom: 
                    configMapKeyRef:
                        name: jaegerenv
                        key: jaeger-http-url
          imagePullPolicy: Always
