apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqldb
data:
  database-name: restapi
  database-service: mysql-demo-project
  database-port: 3306
--- 
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb
type: generic
data:
  database-password: password
  database-user: root
---
apiVersion: v1
kind: Service
metadata:
    name: userService
    labels:
    app: userService
spec:
    selector:
        app: userService
    ports:
        - port: 80
        name: http
        targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userService
  template:
    metadata:
      labels:
        app: userService
    spec:
      containers:
        - name: app
          image: rajeshramawat/userservice
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              valueFrom: 
                    configMapKeyRef:
                        name: mysqldb
                        key: database-service
            - name: MYSQL_PORT
              valueFrom: 
                    configMapKeyRef:
                        name: mysqldb
                        key: database-port
            - name: MYSQL_DB_NAME
              valueFrom: 
                    configMapKeyRef:
                        name: mysqldb
                        key: database-name
            - name: USERNAME
              valueFrom:
                    secretKeyRef:
                        name: mysqldb
                        key: database-user
            - name: PASSWORD
              valueFrom:
                    secretKeyRef:
                        name: mysqldb
                        key: database-password
          imagePullPolicy: Always
